[tidb]
host = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
port = 4000
user = "ax6KHc1BNkyuaor.root"
password = "EP8isIWoEOQk7DSr"
database = "sensor"

[security]
secret_key = "12b5112c62284ea0b3da0039f298ec7a85ac9a1791044052b6df970640afb1c5"